# sidebar navigation
mode: blog
nav:
  - Archives
  - Categories
  - Tags
  - About

book_mode_home: /home # filename under source/_posts/
book_mode_menu:
  - name:
    link: 
    groupof:
    - name:
      link:
      groupof:
      - name:
        link:

lightgallery: false

friends:
  - name: SITE A
    url: /site_a_url
  - name: SITE B
    url: /site_b_url