# sidebar navigation
mode: blog
nav:
  - Archives
  - Categories
  - Tags
  - About

book_mode_home: /home
book_mode_menu:
  - name:
    link: 
    groupof:
    - name:
      link:
      groupof:
      - name:
        link:

lightgallery: false

friends:
  - name: a
    url: aaa
  - name: b
    url: bbb